<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="81" started-at="2019-10-30T04:07:55Z" finished-at="2019-10-30T04:07:55Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="81" started-at="2019-10-30T04:07:55Z" finished-at="2019-10-30T04:07:55Z">
      <class name="testNG_Test_Cases.TestNG_Simple_Test">
        <test-method status="FAIL" signature="testDashboard()[pri:0, instance:testNG_Test_Cases.TestNG_Simple_Test@5afa04c]" name="testDashboard" duration-ms="19" started-at="2019-10-30T09:37:55Z" finished-at="2019-10-30T09:37:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at testNG_Test_Cases.TestNG_Simple_Test.testDashboard(TestNG_Simple_Test.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDashboard -->
        <test-method status="PASS" signature="testLogin()[pri:0, instance:testNG_Test_Cases.TestNG_Simple_Test@5afa04c]" name="testLogin" duration-ms="4" started-at="2019-10-30T09:37:55Z" finished-at="2019-10-30T09:37:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="testProfile()[pri:0, instance:testNG_Test_Cases.TestNG_Simple_Test@5afa04c]" name="testProfile" duration-ms="2" started-at="2019-10-30T09:37:55Z" finished-at="2019-10-30T09:37:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testProfile -->
      </class> <!-- testNG_Test_Cases.TestNG_Simple_Test -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
